version: 1.0.8.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - gh-pages
image: Visual Studio 2017
configuration:
- Release
environment:
  gp_build_user: ObsidianMinor
  gp_build_user_email: obsidianminor@gmail.com
  access_token:
    secure: hbO0PhmlEaYZiDRbliEBxSbB8qQBnE0e4XxRvW7GhLRdlYO5/CGwbsaMgUBMov1N
build_script:
- ps: >-
    if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -or $env:APPVEYOR_REPO_BRANCH -eq "master")

    {
        git checkout $env:APPVEYOR_REPO_BRANCH -q
        cinst docfx -y
    }

    dotnet restore src/Gfycat.Net/Gfycat.Net.csproj

    dotnet restore src/Gfycat.Net.Analytics/Gfycat.Net.Analytics.csproj

    dotnet restore tests/Gfycat.Net.Tests/Gfycat.Net.Tests.csproj

    if(-Not $env:APPVEYOR_REPO_BRANCH -eq "master")

    {
        dotnet build Gfycat.Net.sln --configuration Release /p:Version=$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH
    }

    else

    {
        dotnet build Gfycat.Net.sln --configuration Release /p:Version=$env:APPVEYOR_BUILD_VERSION
    }

    if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -or $env:APPVEYOR_REPO_BRANCH -eq "master")

    {
        CD docs
        docfx docfx.json
        git config --global credential.helper store
        Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
        git config --global user.email $env:gp_build_user_email
        git config --global user.name $env:gp_build_user

        git clone https://github.com/ObsidianMinor/Gfycat.Net.git -b gh-pages origin_site
        Copy-Item origin_site/.git _site -recurse
        CD _site
        git add .
        git commit -m "CI Updates"
        git push origin gh-pages
        CD ..\..
    }
test_script:
- ps: dotnet test tests/Gfycat.Net.Tests/Gfycat.Net.Tests.csproj
artifacts:
- path: '**/Release/*$(APPVEYOR_BUILD_VERSION)*.nupkg'
  name: Nuget Packages
deploy:
- provider: NuGet
  api_key:
    secure: lIIha19su56DoSb9z5LilA8cIKhNsph/NqxUxIYdh+4XJq67ZRt+1Fkohqx8RHh0
  artifact: /.*\.nupkg/
  on:
    branch: master
- provider: NuGet
  server: https://www.myget.org/F/gfycat-net/api/v2/package
  api_key:
    secure: dC/r9sWakZvZKWAD+yiakvdXWOZWvCfRtDFkIb8B19T1X0WoZqblJFkfpnKRsmhd
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: dev
